#!/bin/bash
#
# Update (pull) working copies under each of the given project roots.
# By default, it looks into '~/workspace'.
#
# Usage: $0 [PROJECTS_ROOT_1] [PROJECTS_ROOT_2] .. [PROJECTS_ROOT_n]
#


## configurable vars
DEFAULT_PROJECTS_ROOTS=~/workspace


## internal vars
[ -n "$1" ] && PROJECTS_ROOTS=$@ || PROJECTS_ROOTS=$DEFAULT_PROJECTS_ROOTS


## imports
. $( dirname ${BASH_SOURCE[0]} )/git_functions.sh  || {
  echo -e "\n\tERR: cannot import git_functions.sh. Exiting\n"
  exit 1
}


## loop over all of the roots
for PROJECTS_ROOT in $PROJECTS_ROOTS ; do

  ## loop over all of the subdirs in a root
  for PROJECT_DIR in $( find $PROJECTS_ROOT -maxdepth 1 -mindepth 1 -type d ) ; do
    PROJECT=$( basename "$PROJECT_DIR" )
    echo -e "\nUpdating $PROJECT\n"
    cd "$PROJECT_DIR" &&
    git_pull_safe || {
      FAILED="$FAILED $PROJECT"
    }
    echo -e "\n\n"
  done

done


## finally report any error that occured
echo
echo
if [ -n "$FAILED" ] ; then
  echo " **** WARNING ****"
  echo "errors occured for the following projects:"

  for proj in $FAILED ; do
    echo " - $proj"
  done
  echo
  exit 1
else
  exit 0
fi
